### ISSUE TITLE
Single Pass VR does not work

### ISSUE THREAD

**Issue by EddieSoloProjects** [EdoFrank/RainDropEffect#3]
I can't get this to work in single pass VR.

Also got this error in latest unity:
Shader error in 'RainDrop/Internal/RainDistortion (Forward)': failed to open source file: 'RainDropGlobal.cginc' at line 36 (on d3d11)

**Comment by EddieSoloProjects** [comment]
My mistake. Fog Volume 3 was causing the issue with it in single pass mode.

**Comment by EdoFrank** [comment]
Now I am working for updating for Unity2017.2.
Anyway, thank you for your issue!

**Comment by EddieSoloProjects** [comment]
Thanks It is odd that alone it does work in single pass mode. But I tried it with Volume fog 3 and Hx Volumetric Lighting and it instantly breaks the game. Something is making it not play well with other tools.
